[project]
name = "afterquote"
version = "0.3.0"
description = "Synthetic after-hours quote generator"
authors = [{ name = "Mohammad Junaid", email = "mohammadjunaiduk@gmail.com" }]
readme = "README.md"
license = "MIT"
requires-python = ">=3.8"

dependencies = [
    "yfinance>=1.4.1",
    "pandas>=2.0",
    "pytz>=2024",
    "pandas_market_calendars>=5.0",
]

[project.optional-dependencies]
dev = [
    "black",
    "pylint",
]
test = [
    "pytest",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
